### ISSUE TITLE
Do Thunderbolt 4 eGPUs work in Linux?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [chrultrabook/docs#143]
Has anyone tried using an eGPU with a Chromebook through Thunderbolt 4 on Linux? Are there any additional issues or special instructions in addition to what can be found in https://wiki.archlinux.org/title/External_GPU?

**Comment by ethanaobrien** [comment]
This question should be asked in the chrultrabook forum

https://forum.chrultrabook.com/

**Comment by ChocolateLoverRaj** [comment]
@ethanaobrien thanks for sharing the link, I didn't know that there was a Chrultrabook Forum. I'm guessing Discord has been replaced with the forum. Very nice.

**Comment by ethanaobrien** [comment]
Correct
