### ISSUE TITLE
SEO: Headers

### ISSUE THREAD

**Issue by ninelore** [chrultrabook/docs#152]
We got many h3 (###) without prior h2 (##)

They need to be changed to h2

**Comment by marcsadler** [comment]
I could do that since I think I'm responsible for some of them. There are also some instances of spacers before a h2 that I'd like to remove. I can't commit to your PR so I'll just open a new PR for the ``seo`` branch?

**Comment by ninelore** [comment]
You can go ahead

**Comment by marcsadler** [comment]
I'm not sure how to link my PR to this issue. Anyway, I would really appreciate it if you could review when convenient. Thank you!
