### ISSUE TITLE
[Workarounding] Samung 3 CELES notebook

### ISSUE THREAD

**Issue by tjaslz** [chrultrabook/docs#20]
Hi. I propose to you bypassing for Samsung Notebook 3 CELS:

bcdedit /set {default} useplatformclock on

Fix Celes issues, Let me notify sucess or fail.

**Comment by meghan06** [comment]
The workaround can be found on CoolStar's website. The documentation is very much still a work in progress. The CELES workaround will be implemented sometime soon.
