### ISSUE TITLE
Docs about making top row keys non-function keys by default on windows

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [chrultrabook/docs#63]
Me and some other people like to have the same top row behavior as Chrome OS (by default it does things like change brightness and volume, and when u hold the Search key it does F1, F2, ...

I forked the keyboard tester to do this: https://github.com/ChocolateLoverRaj/VivaldiKeyboardTester/tree/brightness-only

Can I add instructions for people who also want to do this on windows:
- Download https://github.com/ChocolateLoverRaj/VivaldiKeyboardTester/raw/brightness-only/croskbsettings.bin
- Copy the file to `C:\Windows\System32\drivers\croskbsettings.bin`
- Execute `C:\Program Files\crosec\croskbreload.exe`

I'll probably wait for the huge rewrite of the docs to make this change.

**Comment by meghan06** [comment]
Rewrite will take a bit, (hopefully not too long), as of right now I'm thinking you could put this information in the Post Install page.

**Comment by meghan06** [comment]
@ChocolateLoverRaj Double check if any of the steps have changed since creating the issue, I'll be adding it soon.

**Comment by ChocolateLoverRaj** [comment]
I tried it 12 days ago and it worked on my redrix. I don't have a device to test it on right now.

**Comment by meghan06** [comment]
GitHub is broken as fuck.

Anyways @coolstar can you review?

Thansk!

**Comment by ChocolateLoverRaj** [comment]
Btw @meghan06 I double checked and it worked on my jinlon on Wednesday

**Comment by WeirdTreeThing** [comment]
This is gonna be a feature in chrultrabook controller.
