### ISSUE TITLE
Docs about dual booting chrome os and Fedora on RW_LEGACY edk2

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [chrultrabook/docs#71]
Idk where to put this so I'm just writing it in this issue:

This guide is for Chromebooks which support RW_LEGACY and use the edk2 bootloader for RW_LEGACY. If you do not want to keep Chrome OS, don't follow this guide, you can just delete all the partitions. If you want to install a linux distro other than Fedora you can probably do it, but I only tested Fedora.

Tested with: `redrix` with Fedora.

- Make sure you're in developer mode with standard ChromeOS partitions.
- Boot into Chrome OS. Sign in as guest because if you login you'll have to login again later anyways.
- **All of the data in your internal storage will be wiped, so make sure to backup everything you don't want to lose**
- Go into Crosh -> Shell
- Run [`chrx`](https://chrx.org/): `curl https://chrx.org/ | sudo tar xzfC - /usr/local && chrx`. Decide how much space to give to Fedora
- Reboot into Chrome OS. The Chromebook will say that it's repairing itself. Keep booting from internal storage until it successfully boots. You can sign in and you will stay signed in.
- Go into Crosh -> Shell
- Run `curl https://chrx.org/ | sudo tar xzfC - /usr/local && chrx -d ubuntu`
- Command should run successfully
- At this point, `Ctrl + L` **will not work**
- Install RW_LEGACY using mrchromebox's firmware utility script
- Plug in a USB drive containing a Fedora live USB
- Reboot
- Select "Alternative bootloader" -> "edk2"
- Press `Esc` when you see the coreboot logo
- Boot from the USB drive
- Choose custom install in the Fedora installation
- For the `/` partition, choose the parition which contains Ubuntu. This will probably be in partition `7` (update these docs if you are *sure* that it is on this partition). Click on format and make it `/`. I used `ext4`, but `btrfs` might work too. For the `/boot/efi` partition, choose the existing EFI partition. This will probably be in partition `12` (update these docs if you are *sure* that it is on this partition).
- Click "Install"
- Fedora should install successfully
- If everything went right, you have successfully dual-booted your Chromebook with Chrome OS (which can be accessed by booting internal storage when you turn on your chromebook). 
- Shut down or reboot to exit the live USB Fedora
- To boot Chrome OS, select boot from internal storage. To boot Fedora, select alternative bootloader -> "edk2".
- Next steps: Setup Fedora by applying fixes such as audio, keyboard shortcuts, and other hardware.

**Comment by WeirdTreeThing** [comment]
Steps should be more generalized

**Comment by ChocolateLoverRaj** [comment]
> Steps should be more generalized

@WeirdTreeThing do you mean it should work with more than just Fedora?

**Comment by WeirdTreeThing** [comment]
and less device specific

**Comment by ChocolateLoverRaj** [comment]
> and less device specific

1. I'm guessing on devices with SeaBios `chrx` will still work
2. I'm pretty sure there are a lot of chromebooks which use `edk2` so isn't that covering a lot of chromebooks?

**Comment by ChocolateLoverRaj** [comment]
also it could work on Ubuntu, Pop!_OS, and other distros but I cannot be sure since I only tried it with Fedora. I don't want to test the setup again.

**Comment by WeirdTreeThing** [comment]
> I'm guessing on devices with SeaBios chrx will still work

chrx is independent of the payload but OSes might not like the legacy boot/ChromeOS hybrid, not sure

> I'm pretty sure there are a lot of chromebooks which use edk2 so isn't that covering a lot of chromebooks?

Yes but there's more to it. Your instructions say to press the Alternate Bootloader button on startup but that only applies to new devices with the revamped dev mode screen. You also say that the internal drive is most likely /dev/nvme0n1 but that obviously is different between devices.

**Comment by meghan06** [comment]
>You also say that the internal drive is most likely /dev/nvme0n1 but that obviously is different between devices.
@ChocolateLoverRaj  you can just notify the user that it can also show up as  `sda` or `mmcblk` depending on your device

**Comment by ChocolateLoverRaj** [comment]
I edited it so it just says "partition #" instead of specifically `nvme0n1p#`

**Comment by WeirdTreeThing** [comment]
On devices with the old dev screen, ctrl + l usually works. There are some exceptions like glk where you need to directly press 2.

**Comment by ChocolateLoverRaj** [comment]
If you feel sure that it will work we can add instructions for non-edk2 but I don't think we should without actually testing the steps on a device with the old dev screen.

**Comment by WeirdTreeThing** [comment]
Once CRAP is ready, we'll make a dualbooting guide.

**Comment by marcsadler** [comment]
> Once CRAP is ready, we'll make a dualbooting guide.

Please keep the name.

**Comment by joebobbio** [comment]
Closed (dead)

**Comment by ChocolateLoverRaj** [comment]
Btw I just used my own guide and it's working.
