### ISSUE TITLE
Redrix linux guide

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [chrultrabook/docs#72]
Redrix has more hardware difficulties than most Chromebooks, so I will make a guide for other redrix users (and myself):

### What works OOTB:
- Touchscreen
- Wifi / Bluetooth
- Keyboard
- Side volume keys
- Keyboard light
- Clicking the touchpad (and getting haptic feedback)

### What works after installing fixes:
- Speakers
- Microphone
- Moving the cursor with touchpad

### What doesn't work (as of now):
- Camera
- Fingerprint Reader

### Fix Touchpad
Create a file `/etc/libinput/local-overrides.quirks` with these contents:
```
[Google Chromebook Redrix]
MatchUdevType=touchpad
MatchName=ELAN2703:00 04F3:323B Touchpad
MatchDMIModalias=dmi:*pn*Redrix*
ModelChromebook=1
AttrPressureRange=-0:-2
AttrThumbPressureThreshold=45
AttrPalmPressureThreshold=2500
```
Touchpad will start working work on next boot

### Fix Speakers and Microphone
Follow the normal chromebook-linux-audio script. It will make speakers and microphone work.

### Fix Camera (WIP, doesn't work yet, results in a black rectangle camera)
> This is a Fedora-specific solution. Other distros probably have solutions but this guide doesn't have them.
#### Add RPM Fusion Repositories
Follow [this guide](https://rpmfusion.org/Configuration) to add both `free` and `nonfree` repositories.

#### Install IPU6
Steps are from [this guide](https://hansdegoede.livejournal.com/27276.html)

Run
```sh
sudo dnf update \
  --enablerepo=updates-testing \
  --enablerepo=rpmfusion-free-updates-testing \
  --enablerepo=rpmfusion-nonfree-updates-testing \
  'kernel*' '*v4l2loopback' -y

sudo dnf install \
  --enablerepo=updates-testing \
  --enablerepo=rpmfusion-free-updates-testing \
  --enablerepo=rpmfusion-nonfree-updates-testing \
  akmod-intel-ipu6 -y
  ```

Microphone will start working from the next boot

**Comment by meghan06** [comment]
I don't think a guide for redrix only is appropriate for the docs. Maybe integrate this into a personal repo.

**Comment by jwrdegoede** [comment]
I just stumbled over this while looking at the Chromebook Linux Compatibility google-docs spreadsheet.

The community has been working on an opensource stack for IPU6 cameras and I have recently published a COPR (Fedora PPA) repo with this stack for users to test. This has been successfully tested on a "HP Spectre x360 13.5 (2023 model, hi556 sensor)", so it would be interesting to see if this works oh the Redrix chromebook too.

Here is a blogpost announcing the COPR:
https://hansdegoede.dreamwidth.org/28153.html

**Comment by ChocolateLoverRaj** [comment]
I do not have a redrix anymore so I can't test it.

**Comment by WeirdTreeThing** [comment]
@gxsw has a RPL kano with IPU6 and was looking to try to get the camera working

**Comment by gxsw** [comment]
I have this opensource IPU6 stack running fine for over a month now on my productive RPL kano with Fedora

**Comment by ChocolateLoverRaj** [comment]
@jwrdegoede I tried your instructions to enable ipu6. The camera turns on and works, except there are some issues:
1. There is a sound coming from my Chromebook while the camera is being used. It starts immediately when I see the camera. This happens when I run `qcam` but not with https://webcamera.io on firefox
2. The video in qcam seems to be squished to be too short
3. On both `qcam` and Firefox there is a beige tint to the entire video. If I hold a white paper up to the camera it looks beige.

**Comment by ChocolateLoverRaj** [comment]
Also it seems like the kernel that comes with the open source ipu6 is old and has bugs related to https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/70. I'm on `6.7.1-200.1.ipu6.fc39.x86_64`

**Comment by ChocolateLoverRaj** [comment]
@jwrdegoede I can confirm that the kernel that your open source ipu6 packages come with is incompatible with @WeirdTreeThing 's audio script. If you build it from the latest kernel the audio will probably work

**Comment by WeirdTreeThing** [comment]
Saying it doesn't work without providing logs is not helpful.

**Comment by ChocolateLoverRaj** [comment]
Ok I'll record logs with the logs script

**Comment by WeirdTreeThing** [comment]
It does appear to be that same issue

**Comment by ChocolateLoverRaj** [comment]
> I have this opensource IPU6 stack running fine for over a month now on my productive RPL kano with Fedora

@gxsw Which kernel version are you using? Do you get the same no audio issue? Are you using kernel `6.7.0-68.1.ipu6`?

I'm going to try downgrading to `6.7.0-68.1.ipu6` and see if that fixes audio on Redrix.

**Comment by gxsw** [comment]
@ChocolateLoverRaj 
currently I have no access to my kano. But as far as I remember I did not change the kernel and was using recent Fedora standard kernels. I will contact you as soon as I have access to my kano again to verify.

(btw are you the creator of the CR50 debug board? I got one via ebay! really great, thanks for providing these to the community!)
