### ISSUE TITLE
Add automated firmware builder to custom coreboot section

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [chrultrabook/docs#81]
I made an automated Full ROM and altfw UEFI builder: https://github.com/ChocolateLoverRaj/scripts. It is much easier for simple things like changing the logo and timeout.

**Comment by WeirdTreeThing** [comment]
This just makes it easier for clueless people to brick their devices

**Comment by ChocolateLoverRaj** [comment]
Explain

**Comment by WeirdTreeThing** [comment]
You are enabling people that don't know how to compile coreboot to flash custom builds which always has the chance of bricking

**Comment by meghan06** [comment]
Closing for now, the room for error is too high.

**Comment by ChocolateLoverRaj** [comment]
People who don't know how to build coreboot can still use the firmware Utility script to have the same chance of bricking their Chromebook.

**Comment by meghan06** [comment]
Compiling coreboot is kind of like a screening, it filters out the people who know what theyre doing. If a user does not know how to compile coreboot they should not be playing with flashrom.

**Comment by meghan06** [comment]
Right, but the firmware utility script automatically flashes firmware for you. You need to manually flash custom ROMs and some zero clue how and end up doing random thinggs.
