### ISSUE TITLE
Markdown consistency

### ISSUE THREAD

**Issue by ninelore** [chrultrabook/docs#87]
While Markdown is very forgiving with bad formatting, we should bring the docs to a common markdown formatting standard.

Selection of issues:

- Both too many and no blank lines. There should be only one empty line between elements
- Heading order: `#` -> `##` - > `###` -> `####`; No `****'` as headers
- Trailing spaces
- Inconsistent horizontal line `-` count (common is x3)
- ...

**Comment by meghan06** [comment]
For anybody contributing to the docs,

- Title pages should be `##`, and each section in a page should be `###`.
- If making a new page, the name of it should be short and concise, preferably 2 words or less.
- ...

**Comment by ninelore** [comment]
Page Title must be # or its another markdown violation

> Heading order: # -> ## - > ### -> ####; No ****' as headers

**Comment by WeirdTreeThing** [comment]
Should this info be put in the README or a separate page for contributing info?

**Comment by ninelore** [comment]
We will put it in contributing once initial fixes are complete

**Comment by ethanaobrien** [comment]
Can this be closed

**Comment by ninelore** [comment]
nope, my markdown linter still screams at me

**Comment by ninelore** [comment]
#152 is related

**Comment by ninelore** [comment]
fixed in #191
